on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: rethab/composite-action-test
          ref: main
          path: .actions/composite
      - uses: ./.actions/composite
